name: Security Scan

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  gitleaks:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: peer-network/peer_global_security/.github/workflows/gitleaks.yml@main
        with:
          config: gitleaks.toml
